[package]
name = "basic-node-firewall-loader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { version = ">=0.11", features=["async_tokio"] }
aya-log = "0.1"
basic-node-firewall-common = { path = "../basic-node-firewall-common", features=["user"] }
anyhow = "1.0.42"
clap = { version = "3.1", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
bytes = "1"
env_logger = "0.8.4"

[[bin]]
name = "basic-node-firewall-loader"
path = "src/main.rs"
